package org.basex.core;

/**
 * Info listener, receiving and handling information generated during the evaluation
 * of a command or query.
 *
 * @author BaseX Team 2005-16, BSD License
 * @author Christian Gruen
 */
public interface InfoListener {
  /**
   * Information generated by a command or query.
   * @param info info to be processed
   */
  void info(String info);
}
