package org.basex.core;

/**
 * Info listener, receiving and handling information generated during the evaluation
 * of a command or query.
 *
 * @author BaseX Team 2005-13, BSD License
 * @author Christian Gruen
 */
public interface InfoListener {
  /**
   * Processes information generated by a process.
   * @param info info to be processed
   */
  void info(final String info);
}
