package org.basex.core;

/**
 * Trace listener, passes on trace output during the evaluation of a query.
 *
 * @author BaseX Team 2005-16, BSD License
 * @author Christian Gruen
 */
public interface TraceListener {
  /**
   * Information generated by a query.
   * @param info info to be processed
   */
  void info(String info);
}
