blank_issues_enabled: false
contact_links:
  - name: BaseX Mailing List
    url: https://mailman.uni-konstanz.de/mailman/listinfo/basex-talk
    about: Questions, feature requests and unconfirmed bugs are best directed to the BaseX mailing list.
  - name: GitHub Community Support
    url: https://github.community/
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.
