blank_issues_enabled: true
contact_links:
  - name: BaseX Mailing List
    url: https://mailman.uni-konstanz.de/mailman/listinfo/basex-talk
    about: Questions, feature requests and unconfirmed bugs are best directed to the BaseX mailing list.
  - name: BaseX Mailing List: Archive
    url: https://www.mail-archive.com/basex-talk@mailman.uni-konstanz.de/
    about: Check out the mailing list archive for past discussions.
  - name: GitHub Community Support
    url: https://github.community/
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.
