#!/bin/bash

# Path to this script
PWD=`dirname $0`

# Path to class directory (target/classes) or BaseX.jar
BXPATH=$PWD/../target/classes

# Assign more memory
VM=-Xmx1g

# Run BaseX
java -cp "$BXPATH" $VM org.basex.BaseX "$@"
