#!/bin/bash

# Path to this script
FILE="${BASH_SOURCE[0]}"
while [ -h "$FILE" ] ; do
  SRC="$(readlink "$FILE")"
  FILE="$( cd -P "$(dirname "$FILE")" && \
           cd -P "$(dirname "$SRC")" && pwd )/$(basename "$SRC")"
done
BXAPI="$( cd -P "$(dirname "$FILE")/.." && pwd )"
BX="$( cd -P "$BXAPI/../basex" && pwd )"

# API, core, and library classes
CP="$BXAPI/target/classes"
CP="$CP$(for JAR in "$BXAPI"/lib/*.jar; do echo -n ":$JAR"; done)"
CP="$CP:$BX/target/classes"
CP="$CP$(for JAR in "$BX"/lib/*.jar; do echo -n ":$JAR"; done)"

# Options for virtual machine
VM=-Xmx512m

# Run code
java -cp "$CP" $VM org.basex.api.BaseXHTTP "$@" stop
