#!/bin/bash

# Path to this script
PWD=`dirname $0`

# Paths to distributed files or source directories
#BXPATH=basex.jar
BXPATH=$PWD/../target/classes

# Options for virtual machine
VM=

# Run BaseX
java -cp "$BXPATH" $VM org.basex.BaseXClient "$@"
