#!/bin/bash

# Path to this script
PWD=`dirname $0`

# Paths to JAR archives or class files
BASEX=$PWD/../../basex/target/classes
BASEXAPI=$PWD/../target/classes

# Classpath
LIB=$PWD/../lib
CP=$BASEX:$BASEXAPI:$LIB/commons-fileupload-1.2.2.jar:$LIB/commons-beanutils-1.8.2.jar:$LIB/commons-codec-1.4.jar:$LIB/commons-fileupload-1.2.2.jar:$LIB/commons-io-1.4.jar:$LIB/commons-logging-1.1.1.jar:$LIB/jdom-1.1.jar:$LIB/jetty-6.1.26.jar:$LIB/jetty-util-6.1.26.jar:$LIB/log4j-1.2.14.jar:$LIB/lucene-stemmers-3.4.0.jar:$LIB/milton-api-1.6.4.jar:$LIB/mime-util-2.1.3.jar:$LIB/resolver.jar:$LIB/servlet-api-2.5-20081211.jar:$LIB/slf4j-api-1.5.8.jar:$LIB/slf4j-log4j12-1.5.6.jar:$LIB/tagsoup-1.2.jar:$LIB/xmldb-api-1.0.jar:$LIB/xqj-api-1.0.jar

# Options for virtual machine
VM=-Xmx512m

# Run code
java -cp "$CP" $VM org.basex.api.BaseXHTTP "$@"
