#!/bin/bash

# Path to this script
FILE="${BASH_SOURCE[0]}"
while [ -h "$FILE" ] ; do
  SRC="$(readlink "$FILE")"
  FILE="$( cd -P "$(dirname "$FILE")" && \
           cd -P "$(dirname "$SRC")" && pwd )/$(basename "$SRC")"
done
BX="$( cd -P "$(dirname "$FILE")/.." && pwd )"

# Core classes
CP="$BX/target/classes"
CP="$CP$(for JAR in "$BX"/lib/jline*.jar; do echo -n ":$JAR"; done)"

# Run code
java -cp "$CP" org.basex.BaseXClient "$@"
