#!/bin/bash

# Path to this script
PWD=`dirname $0`

# Paths to distributed files or source directories
BASEX=$PWD/../target/classes

# Options for virtual machine
VM=-Xmx512m -server

# Classpath
LIB=$PWD/../lib
CP=$BASEX:$LIB/lucene-analyzers-3.0.2.jar:$LIB/tagsoup-1.2.jar:$LIB/snowball.jar

# Run code
java -cp "$BASEX" $VM org.basex.BaseX -q "$@"
