
            </div> <!-- was opened in header.php -->

            <div id="footer">
                Copyright 2007 DBIS Group. U Konstanz.
<!--
                Design by <a href="http://www.mdibb.net" title="Website of Matt Dibb">Matt Dibb</a> 2006. <a href="http://jigsaw.w3.org/css-validator/check/referer" title="Validate CSS">CSS</a> <a href="http://validator.w3.org/check/referer" title="Validate XHTML">XHTML</a>
-->
            </div>
        </div>
    
    </body>

</html>
