# This property file specifies code completions for the GUI editor.
#
# The string specified as key will be replaced with the assigned value.
# An underscore in the value specifies where the cursor will be located.
# A tilde is replaced with the namespace prefix of a library module (empty in main modules).

ancestor=ancestor::
ancestororself=ancestor-or-self::
attribute=attribute()
child=child::
comment=comment()
consolelog=console.log(_);\n
contains=contains text
context=declare context value := _;\n
copy=copy $_ := \nmodify \nreturn \n
delete=delete node _
descendant=descendant::
declarenamespace=declare namespace _ = '';\n
declareoption=declare option _ '';\n
declareoptionoutput=declare option output:_ '';\n
document-node=document-node()
descendantorself=descendant-or-self::
element=element()
every=every $_ in \nsatisfies
following=following::
followingsibling=following-sibling::
for=for $_ in \nreturn
function=declare function ~_() {\n};\n
import=import module namespace _ = '';\n
insert=insert node _ into
let=let $_ := \nreturn
module=module namespace _ = '';\n
option=declare option _ '';\n
parent=parent::
preceding=preceding::
precedingsibling=preceding-sibling::
processinginstruction=processing-instruction()
record=declare record ~_();\n
rename=rename node _ as
replace=replace node _ with
sliding=for sliding window _ in \nstart when \nreturn
some=some $_ in \nsatisfies
switch=switch (_) {\n  case  return \n  default return \n}
text=text()
try=try {_\n} catch * {\n}
tumbling=for tumbling window _ in \nstart when \nreturn
typeswitch=typeswitch (_) {\n  case  return \n  default return \n}
update=update {_\n}\n
variable=declare variable $~_ := ;\n
