# This property file specifies code completions for the GUI editor.
#
# The string specified as key will be replaced with the assigned value.
# The key spells the completed construct, with hyphens, but without spaces.
# An underscore in the value specifies where the cursor will be located.
# A tilde is replaced with the namespace prefix of a library module (empty in main modules).
#
# Values that start with 'declare' are also proposed as continuations of a prolog declaration.

ancestor=ancestor::
ancestor-or-self=ancestor-or-self::
base-uri=declare base-uri '_';
boundary-space=declare boundary-space _;
child=child::
construction=declare construction _;
contextvalue=declare context value := _;
copy=copy $_ := \nmodify \nreturn
copy-namespaces=declare copy-namespaces _, inherit;
decimal-format=declare decimal-format _;
defaultcollation=declare default collation '_';
defaultdecimalformat=declare default decimal-format _;
defaultelement=declare default element namespace '_';
defaultfunction=declare default function namespace '_';
defaultorder=declare default order empty _;
deletenodes=delete nodes _
descendant=descendant::
descendant-or-self=descendant-or-self::
every=every $_ in \nsatisfies
following=following::
following-sibling=following-sibling::
for=for $_ in \nreturn
function=declare function ~_() {};
if=if (_) then \nelse
import=import module namespace _ = '';
insertnodes=insert nodes _ into
let=let $_ := \nreturn
module=module namespace _ = '';
namespace=declare namespace _ = '';
option=declare option _ '';
optionoutput=declare option output:_ '';
ordering=declare ordering _;
parent=parent::
preceding=preceding::
preceding-sibling=preceding-sibling::
record=declare record ~_();
renamenodes=rename nodes _ as
replacenodes=replace nodes _ with
replacevalue=replace value of nodes _ with
revalidation=declare revalidation skip;
self=self::
sliding=for sliding window _ in \nstart when \nreturn
some=some $_ in \nsatisfies
switch=switch (_) {\n  case  return \n  default return \n}
try=try {_} catch * {}
tumbling=for tumbling window _ in \nstart when \nreturn
typeswitch=typeswitch (_) {\n  case  return \n  default return \n}
update=update {_}
variable=declare variable $~_ := ;
