#!/usr/bin/env bash

# Path to this script
FILE="${BASH_SOURCE[0]}"
while [ -h "$FILE" ] ; do
  SRC="$(readlink "$FILE")"
  FILE="$( cd -P "$(dirname "$FILE")" && \
           cd -P "$(dirname "$SRC")" && pwd )/$(basename "$SRC")"
done
BX="$( cd -P "$(dirname "$FILE")/.." && pwd )"

# Core and library classes
CP="$BX/target/classes$(printf ":%s" "$BX/lib/"*.jar)"

# Options for virtual machine (can be extended by global options)
BASEX_JVM="-Xmx512m $BASEX_JVM"

# Run code
java -cp $CP $BASEX_JVM org.basex.BaseX $@
