#!/usr/bin/env bash

# Path to this script
FILE="${BASH_SOURCE[0]}"
while [ -h "$FILE" ] ; do
  SRC="$(readlink "$FILE")"
  FILE="$( cd -P "$(dirname "$FILE")" && \
           cd -P "$(dirname "$SRC")" && pwd )/$(basename "$SRC")"
done
MAIN="$( cd -P "$(dirname "$FILE")/.." && pwd )"

# Core and library classes
CP=$MAIN/target/classes:$MAIN/lib/custom/*:$MAIN/lib/*:$CLASSPATH

# Run code
exec java -cp "$CP" $BASEX_JVM org.basex.BaseXServer "$@" stop
