#!/usr/bin/env bash

# Path to this script
FILE="${BASH_SOURCE[0]}"
while [ -h "$FILE" ] ; do
  SRC="$(readlink "$FILE")"
  FILE="$( cd -P "$(dirname "$FILE")" && \
           cd -P "$(dirname "$SRC")" && pwd )/$(basename "$SRC")"
done
BX="$( cd -P "$(dirname "$FILE")/.." && pwd )"

# Core and library classes
CP="$BX/target/classes$(printf ":%s" "$BX/lib/"*.jar)"

# Options for virtual machine
VM=

general_args=( )
vm_args=( )
while (( $# )) ; do
  if [[ $1 = "-X" ]] ; then
    vm_args+=( "$2" )
    shift 2
  else
    general_args+=( "$1" )
    shift
  fi
done

# Run code
java -cp "$CP" $VM "${vm_args[@]}" org.basex.BaseXClient "${general_args[@]}"
